# Generated by Django 3.2.3 on 2021-11-04 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brach', models.CharField(max_length=50)),
                ('created_Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email_teacher', models.EmailField(max_length=254)),
                ('phone_teacher', models.CharField(max_length=50)),
                ('image', models.ImageField(default='default.pg', upload_to='teacher')),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('speciality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.brach')),
            ],
        ),
    ]
